spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
        username:root
        password:123456
        url:jdbc:mysql://192.168.0.103/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
context-path: /sell
logging:
  pattern:
    level: debug
    console: "%d - %msg%n"
#    path: /var/log/tomcat
# 默认文件名称是 spring.log D:\spring.log
  path: D:\
#  file: D:\sell.log
