spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.103/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##    path: /var/log/tomcat
## 默认文件名称是 spring.log D:\spring.log，path 和 file 配置一个即可。
#  path: D:\
##  file: D:\sell.log
#
## 日志级别
#  level:
##    全局设定日志级别
##    root: debug
##    设置单个类的日志级别
##    com.springbootwx.sell: debug